baseURL = "https://ation-dev.github.io/datamask.dev/"
title = "Datamask"
theme = "hugo-book"

enableRobotsTXT = true
markup.goldmark.renderer.unsafe = true

[params]
  BookTheme = "light"          # auto | dark | light
  BookSearch = false          # keep minimal for proposal-first
  BookLogo = ""               # optional later
  BookToC = true              # table of contents on long pages
  BookSection = "docs"           # keep default behavior

